# Generated by Django 3.2.6 on 2021-09-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='phoneno',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
