# Generated by Django 3.2.6 on 2021-09-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_games_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=120)),
                ('lname', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(max_length=256)),
            ],
        ),
    ]
