# Generated by Django 3.2.6 on 2021-09-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='gameDate',
            field=models.DateField(default='2021-10-21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='gameSlot',
            field=models.CharField(default='10', max_length=20),
            preserve_default=False,
        ),
    ]
